// Mock Restaurants Data
export const mockRestaurants = [
  {
    id: 1,
    name: "Dhaka Biryani House",
    cuisine: "Bangladeshi",
    rating: 4.8,
    deliveryTime: "25-35",
    deliveryFee: 40,
    minOrder: 150,
    image: "🍛",
    popular: true,
    priceRange: "$$",
    discount: 20,
    fastDelivery: false,
    topDeal: true,
  },
  {
    id: 2,
    name: "Pizza Paradise",
    cuisine: "Italian",
    rating: 4.6,
    deliveryTime: "30-40",
    deliveryFee: 50,
    minOrder: 200,
    image: "🍕",
    popular: true,
    priceRange: "$$$",
    discount: 0,
    fastDelivery: false,
    topDeal: true,
  },
  {
    id: 3,
    name: "Burger Kingdom",
    cuisine: "American",
    rating: 4.5,
    deliveryTime: "20-30",
    deliveryFee: 35,
    minOrder: 120,
    image: "🍔",
    popular: false,
    priceRange: "$$",
    discount: 30,
    fastDelivery: true,
    topDeal: false,
  },
  {
    id: 4,
    name: "Sushi Master",
    cuisine: "Japanese",
    rating: 4.9,
    deliveryTime: "35-45",
    deliveryFee: 60,
    minOrder: 250,
    image: "🍣",
    popular: true,
    priceRange: "$$$",
    discount: 0,
    fastDelivery: false,
    topDeal: true,
  },
  {
    id: 5,
    name: "Curry Express",
    cuisine: "Indian",
    rating: 4.4,
    deliveryTime: "25-35",
    deliveryFee: 40,
    minOrder: 150,
    image: "🍛",
    popular: false,
    priceRange: "$$",
    discount: 25,
    fastDelivery: false,
    topDeal: false,
  },
  {
    id: 6,
    name: "Thai Street Food",
    cuisine: "Thai",
    rating: 4.7,
    deliveryTime: "30-40",
    deliveryFee: 45,
    minOrder: 180,
    image: "🍜",
    popular: false,
    priceRange: "$$",
    discount: 15,
    fastDelivery: true,
    topDeal: false,
  },
];

// Cuisine Categories with Icons
export const cuisineCategories = [
  { id: "All", name: "All", icon: "🍽️" },
  { id: "Bangladeshi", name: "Bangladeshi", icon: "🍛" },
  { id: "Italian", name: "Italian", icon: "🍕" },
  { id: "American", name: "American", icon: "🍔" },
  { id: "Japanese", name: "Japanese", icon: "🍣" },
  { id: "Indian", name: "Indian", icon: "🍛" },
  { id: "Thai", name: "Thai", icon: "🍜" },
];

// Mock Menu Items by Restaurant
export const mockMenuItems = {
  1: [ // Dhaka Biryani House
    {
      id: 101,
      name: "Kacchi Biryani",
      category: "Main Course",
      description: "Authentic Dhaka-style mutton biryani with basmati rice",
      price: 320,
      image: "🍛",
      variants: [
        { name: "Regular", price: 320 },
        { name: "Large", price: 450 },
      ],
      popular: true,
    },
    {
      id: 102,
      name: "Chicken Roast",
      category: "Main Course",
      description: "Spicy marinated chicken with traditional spices",
      price: 180,
      image: "🍗",
      variants: [
        { name: "Half", price: 180 },
        { name: "Full", price: 320 },
      ],
    },
    {
      id: 103,
      name: "Beef Tehari",
      category: "Main Course",
      description: "Flavorful beef cooked with aromatic rice",
      price: 280,
      image: "🍚",
      variants: [
        { name: "Regular", price: 280 },
        { name: "Large", price: 380 },
      ],
    },
    {
      id: 104,
      name: "Borhani",
      category: "Beverages",
      description: "Traditional yogurt drink",
      price: 40,
      image: "🥤",
    },
    {
      id: 105,
      name: "Shahi Firni",
      category: "Desserts",
      description: "Creamy rice pudding with cardamom",
      price: 80,
      image: "🍮",
    },
  ],
  2: [ // Pizza Paradise
    {
      id: 201,
      name: "Margherita Pizza",
      category: "Pizza",
      description: "Classic tomato sauce, mozzarella, and basil",
      price: 450,
      image: "🍕",
      variants: [
        { name: "Small (8\")", price: 450 },
        { name: "Medium (12\")", price: 680 },
        { name: "Large (16\")", price: 950 },
      ],
      popular: true,
    },
    {
      id: 202,
      name: "Pepperoni Feast",
      category: "Pizza",
      description: "Loaded with pepperoni and extra cheese",
      price: 550,
      image: "🍕",
      variants: [
        { name: "Small (8\")", price: 550 },
        { name: "Medium (12\")", price: 780 },
        { name: "Large (16\")", price: 1050 },
      ],
      popular: true,
    },
    {
      id: 203,
      name: "Garlic Bread",
      category: "Appetizers",
      description: "Crispy bread with garlic butter",
      price: 150,
      image: "🥖",
    },
    {
      id: 204,
      name: "Caesar Salad",
      category: "Salads",
      description: "Fresh romaine with parmesan and croutons",
      price: 250,
      image: "🥗",
    },
    {
      id: 205,
      name: "Tiramisu",
      category: "Desserts",
      description: "Classic Italian dessert",
      price: 280,
      image: "🍰",
    },
  ],
  3: [ // Burger Kingdom
    {
      id: 301,
      name: "Classic Beef Burger",
      category: "Burgers",
      description: "Juicy beef patty with lettuce, tomato, and cheese",
      price: 280,
      image: "🍔",
      variants: [
        { name: "Single", price: 280 },
        { name: "Double", price: 420 },
      ],
      popular: true,
    },
    {
      id: 302,
      name: "Chicken Burger",
      category: "Burgers",
      description: "Crispy chicken with special sauce",
      price: 250,
      image: "🍔",
      variants: [
        { name: "Single", price: 250 },
        { name: "Double", price: 380 },
      ],
    },
    {
      id: 303,
      name: "French Fries",
      category: "Sides",
      description: "Crispy golden fries",
      price: 120,
      image: "🍟",
      variants: [
        { name: "Regular", price: 120 },
        { name: "Large", price: 180 },
      ],
    },
    {
      id: 304,
      name: "Onion Rings",
      category: "Sides",
      description: "Crispy battered onion rings",
      price: 150,
      image: "🧅",
    },
    {
      id: 305,
      name: "Chocolate Shake",
      category: "Beverages",
      description: "Thick chocolate milkshake",
      price: 180,
      image: "🥤",
    },
  ],
  4: [ // Sushi Master
    {
      id: 401,
      name: "California Roll",
      category: "Sushi Rolls",
      description: "Crab, avocado, and cucumber",
      price: 380,
      image: "🍣",
      popular: true,
    },
    {
      id: 402,
      name: "Spicy Tuna Roll",
      category: "Sushi Rolls",
      description: "Fresh tuna with spicy mayo",
      price: 420,
      image: "🍣",
      popular: true,
    },
    {
      id: 403,
      name: "Salmon Sashimi",
      category: "Sashimi",
      description: "Fresh salmon slices (6 pieces)",
      price: 480,
      image: "🍣",
    },
    {
      id: 404,
      name: "Miso Soup",
      category: "Soups",
      description: "Traditional Japanese soup",
      price: 150,
      image: "🍜",
    },
    {
      id: 405,
      name: "Green Tea Ice Cream",
      category: "Desserts",
      description: "Authentic matcha ice cream",
      price: 180,
      image: "🍨",
    },
  ],
};

// Mock Orders Data
export const mockOrders = [
  {
    id: "ORD001",
    restaurantId: 1,
    restaurantName: "Dhaka Biryani House",
    items: [
      { name: "Kacchi Biryani", variant: "Regular", quantity: 2, price: 320 },
      { name: "Borhani", quantity: 2, price: 40 },
    ],
    subtotal: 720,
    deliveryFee: 40,
    total: 760,
    status: "rider_assigned",
    orderTime: "2025-12-16 12:30 PM",
    pin: "8899",
    isActive: true,
  },
  {
    id: "ORD002",
    restaurantId: 2,
    restaurantName: "Pizza Paradise",
    items: [
      { name: "Margherita Pizza", variant: "Medium (12\")", quantity: 1, price: 680 },
      { name: "Garlic Bread", quantity: 1, price: 150 },
    ],
    subtotal: 830,
    deliveryFee: 50,
    total: 880,
    status: "accepted",
    orderTime: "2025-12-16 01:15 PM",
    isActive: true,
  },
  {
    id: "ORD003",
    restaurantId: 3,
    restaurantName: "Burger Kingdom",
    items: [
      { name: "Classic Beef Burger", variant: "Double", quantity: 1, price: 420 },
      { name: "French Fries", variant: "Large", quantity: 1, price: 180 },
    ],
    subtotal: 600,
    deliveryFee: 35,
    total: 635,
    status: "delivered",
    orderTime: "2025-12-15 07:30 PM",
    deliveredTime: "2025-12-15 08:15 PM",
    isActive: false,
  },
  {
    id: "ORD004",
    restaurantId: 4,
    restaurantName: "Sushi Master",
    items: [
      { name: "California Roll", quantity: 2, price: 380 },
      { name: "Miso Soup", quantity: 1, price: 150 },
    ],
    subtotal: 910,
    deliveryFee: 60,
    total: 970,
    status: "delivered",
    orderTime: "2025-12-14 06:00 PM",
    deliveredTime: "2025-12-14 07:10 PM",
    isActive: false,
  },
];

// Order Status Configuration
export const orderStatuses = {
  pending: {
    label: "Pending",
    message: "Waiting for Restaurant...",
    color: "yellow",
    icon: "⏳",
  },
  accepted: {
    label: "Accepted",
    message: "Restaurant accepted your order",
    color: "orange",
    icon: "✓",
  },
  preparing: {
    label: "Preparing",
    message: "Restaurant is preparing your food...",
    color: "orange",
    icon: "👨‍🍳",
  },
  rider_assigned: {
    label: "Rider Assigned",
    message: "Rider is coming!",
    color: "green",
    icon: "🏍️",
  },
  on_the_way: {
    label: "On The Way",
    message: "Your order is on the way!",
    color: "green",
    icon: "🚴",
  },
  out_for_delivery: {
    label: "Out for Delivery",
    message: "Rider is delivering your order!",
    color: "green",
    icon: "🏍️",
  },
  delivered: {
    label: "Delivered",
    message: "Order delivered successfully",
    color: "blue",
    icon: "✅",
  },
  cancelled: {
    label: "Cancelled",
    message: "Order was cancelled",
    color: "red",
    icon: "❌",
  },
};
