// Mock data for testing - will be replaced with actual API calls
export const mockOrders = [
  {
    _id: "ORD001",
    restaurant_id: "1",
    customer_id: "CUST001",
    customer_name: "Ahmed Hassan",
    customer_phone: "+8801712345678",
    items: [
      {
        food_id: "FOOD001",
        food_name: "Grilled Chicken Platter",
        quantity: 2,
        price: 450,
        discount_percentage: 0,
      },
      {
        food_id: "FOOD002",
        food_name: "Caesar Salad",
        quantity: 1,
        price: 250,
        discount_percentage: 10,
      },
    ],
    order_status: "new",
    total_amount: 1125,
    delivery_address: {
      street: "House 23, Road 11",
      city: "Dhaka",
      state: "Dhaka Division",
      zipCode: "1212",
    },
    special_instructions: "Extra sauce please",
    pin1: "1234",
    pin2: "5678",
    assigned_rider_id: null,
    assigned_rider_name: null,
    rejection_reason: "",
    created_at: new Date(Date.now() - 5 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    _id: "ORD002",
    restaurant_id: "1",
    customer_id: "CUST002",
    customer_name: "Fatima Khan",
    customer_phone: "+8801812345678",
    items: [
      {
        food_id: "FOOD003",
        food_name: "BBQ Ribs",
        quantity: 1,
        price: 650,
        discount_percentage: 15,
      },
    ],
    order_status: "preparing",
    total_amount: 552.5,
    delivery_address: {
      street: "Flat 4B, Building 12",
      city: "Dhaka",
      state: "Dhaka Division",
      zipCode: "1213",
    },
    special_instructions: "",
    pin1: "2468",
    pin2: "1357",
    assigned_rider_id: "RIDER001",
    assigned_rider_name: "Karim Uddin",
    rejection_reason: "",
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    _id: "ORD003",
    restaurant_id: "1",
    customer_id: "CUST003",
    customer_name: "Rahul Ahmed",
    customer_phone: "+8801912345678",
    items: [
      {
        food_id: "FOOD001",
        food_name: "Grilled Chicken Platter",
        quantity: 1,
        price: 450,
        discount_percentage: 0,
      },
      {
        food_id: "FOOD004",
        food_name: "Fried Rice",
        quantity: 1,
        price: 200,
        discount_percentage: 0,
      },
    ],
    order_status: "ready",
    total_amount: 650,
    delivery_address: {
      street: "House 45, Road 7",
      city: "Dhaka",
      state: "Dhaka Division",
      zipCode: "1215",
    },
    special_instructions: "Call when you arrive",
    pin1: "3691",
    pin2: "2580",
    assigned_rider_id: "RIDER002",
    assigned_rider_name: "Rahim Miah",
    rejection_reason: "",
    created_at: new Date(Date.now() - 40 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60000).toISOString(),
  },
];

export const mockFoodItems = [
  {
    _id: "FOOD001",
    restaurant_id: "1",
    food_name: "Grilled Chicken Platter",
    food_description: "Tender grilled chicken served with vegetables and sauce",
    food_price: 450,
    food_quantity: 50,
    is_available: true,
    discount_percentage: 0,
    food_category: "Main Course",
    tags: ["chicken", "grilled"],
    average_rating: 4.5,
    rating_count: 45,
    food_images: [],
    createdAt: "2025-12-01T10:00:00.000Z",
    updatedAt: "2025-12-15T14:30:00.000Z",
  },
  {
    _id: "FOOD002",
    restaurant_id: "1",
    food_name: "Caesar Salad",
    food_description: "Fresh romaine lettuce with Caesar dressing and croutons",
    food_price: 250,
    food_quantity: 30,
    is_available: true,
    discount_percentage: 10,
    food_category: "Appetizers",
    tags: ["salad", "vegetarian"],
    average_rating: 4.2,
    rating_count: 32,
    food_images: [],
    createdAt: "2025-12-01T10:00:00.000Z",
    updatedAt: "2025-12-14T09:20:00.000Z",
  },
  {
    _id: "FOOD003",
    restaurant_id: "1",
    food_name: "BBQ Ribs",
    food_description: "Smoky BBQ ribs with special sauce",
    food_price: 650,
    food_quantity: 20,
    is_available: true,
    discount_percentage: 15,
    food_category: "Main Course",
    tags: ["bbq", "ribs"],
    average_rating: 4.8,
    rating_count: 67,
    food_images: [],
    createdAt: "2025-12-01T10:00:00.000Z",
    updatedAt: "2025-12-16T08:15:00.000Z",
  },
  {
    _id: "FOOD004",
    restaurant_id: "1",
    food_name: "Fried Rice",
    food_description: "Special fried rice with vegetables and egg",
    food_price: 200,
    food_quantity: 0,
    is_available: false,
    discount_percentage: 0,
    food_category: "Main Course",
    tags: ["rice", "asian"],
    average_rating: 4.0,
    rating_count: 28,
    food_images: [],
    createdAt: "2025-12-01T10:00:00.000Z",
    updatedAt: "2025-12-16T07:45:00.000Z",
  },
  {
    _id: "FOOD005",
    restaurant_id: "1",
    food_name: "Chocolate Brownie",
    food_description: "Rich chocolate brownie with vanilla ice cream",
    food_price: 180,
    food_quantity: 25,
    is_available: true,
    discount_percentage: 0,
    food_category: "Desserts",
    tags: ["chocolate", "dessert"],
    average_rating: 4.6,
    rating_count: 52,
    food_images: [],
    createdAt: "2025-12-01T10:00:00.000Z",
    updatedAt: "2025-12-15T16:00:00.000Z",
  },
  {
    _id: "FOOD006",
    restaurant_id: "1",
    food_name: "Fresh Juice",
    food_description: "Freshly squeezed orange juice",
    food_price: 120,
    food_quantity: 40,
    is_available: true,
    discount_percentage: 0,
    food_category: "Drinks",
    tags: ["juice", "fresh"],
    average_rating: 4.3,
    rating_count: 38,
    food_images: [],
    createdAt: "2025-12-01T10:00:00.000Z",
    updatedAt: "2025-12-15T11:30:00.000Z",
  },
];

export const mockReviews = [
  {
    review_id: "REV001",
    restaurant_id: "1",
    customer_id: "CUST001",
    customer_name: "Ahmed Hassan",
    rating: 5,
    review_text: "Amazing food! The grilled chicken was perfectly cooked. Will order again!",
    created_at: "2025-12-15T18:30:00.000Z",
  },
  {
    review_id: "REV002",
    restaurant_id: "1",
    customer_id: "CUST004",
    customer_name: "Sara Ali",
    rating: 4,
    review_text: "Good quality food but delivery took a bit long. Overall satisfied.",
    created_at: "2025-12-14T14:20:00.000Z",
  },
  {
    review_id: "REV003",
    restaurant_id: "1",
    customer_id: "CUST005",
    customer_name: "Imran Sheikh",
    rating: 5,
    review_text: "Best BBQ ribs in town! Highly recommend.",
    created_at: "2025-12-13T20:15:00.000Z",
  },
  {
    review_id: "REV004",
    restaurant_id: "1",
    customer_id: "CUST006",
    customer_name: "Nadia Islam",
    rating: 3,
    review_text: "Food was okay, but portion size could be bigger for the price.",
    created_at: "2025-12-12T12:45:00.000Z",
  },
  {
    review_id: "REV005",
    restaurant_id: "1",
    customer_id: "CUST007",
    customer_name: "Kamal Hossain",
    rating: 5,
    review_text: "Excellent service and delicious food. The brownie was heavenly!",
    created_at: "2025-12-11T19:00:00.000Z",
  },
];
